### PR TITLE
Ody Driver Fixes

### PR DESCRIPTION
**Pull request by amystamile-usgs**

### CODE REVIEW

**Comment by amystamile-usgs** [comment]
Seeing an issue with Themis VIR where:

with `sclkCode: -53` and `clockValue: 1023406812.230`

I am seeing two different results:

CSpice `scs2e_c` is returning  `392211096.4307215`.

SpiceyPy `spice.scs2e` is returning `392211095.6221291`.

@acpaquette have you ever run into this before?

**Comment by acpaquette** [comment]
> Seeing an issue with Themis VIR where:
> 
> with `sclkCode: -53` and `clockValue: 1023406812.230`
> 
> I am seeing two different results:
> 
> CSpice `scs2e_c` is returning `392211096.4307215`.
> 
> SpiceyPy `spice.scs2e` is returning `392211095.6221291`.
> 
> @acpaquette have you ever run into this before?

I have not seen this, I would make sure your times are the same to the 16th sig fig and that the codes are the same

**Comment by amystamile-usgs** [comment]
> > Seeing an issue with Themis VIR where:
> > with `sclkCode: -53` and `clockValue: 1023406812.230`
> > I am seeing two different results:
> > CSpice `scs2e_c` is returning `392211096.4307215`.
> > SpiceyPy `spice.scs2e` is returning `392211095.6221291`.
> > @acpaquette have you ever run into this before?
> 
> I have not seen this, I would make sure your times are the same to the 16th sig fig and that the codes are the same

Figured out that python's str() function was dropping the zero and causing it to convert the time for 1023406812.023 instead of 1023406812.230.

**Review by AustinSanders — COMMENTED** [review]
Should be good to go after a changelog entry!

**Review by AustinSanders — APPROVED** [review]

**Pull request merged**
