### PR TITLE
Adding Ale dawn framing camera driver for ISIS3 Labels

### PR DESCRIPTION
**Pull request by antonhibl**
Adding the ALE dawnfc driver, the tests still need to be adapted to use the new isis3 label driver alongside the pds3 label driver. The preliminary comparison of Ale and ISIS outputs at this point looks promising, the ck and spk start/end times still need to be tuned according to the ISIS3 camera model for dawn framing camera.

### CODE REVIEW

**Comment by antonhibl** [comment]
tests _most likely_ will pass for now as they still use the PDS3 label as mentioned above, they will be adjusted in the coming commits to also utilize and test the IsisLabel Ale driver

**Comment by Kelvinrr** [comment]
I dont understand, why is this one still failing?

**Comment by antonhibl** [comment]
@Kelvinrr I believe I still need to add the label in the data area, working on that now

**Comment by Kelvinrr** [comment]
😟 

Screenshot 2023-10-05 at 8 51 43 AM

**Comment by antonhibl** [comment]
it looks like the ubuntu 3.8 runner and the 3.9 ubuntu runner are both failing due to an import in conftest which wasn't touched with this PR, I believe those errors are outside the scope of this PR though

**Comment by Kelvinrr** [comment]
It looks good to me, but Im a little worried about those tests, might be an upstream issue.

**Comment by Kelvinrr** [comment]
yeah, last PR merge is failing. From talking to adam about this the tests were passing before this happened. We should probably try to get these tests back to normal as part of continuous support.

**Review by Kelvinrr — APPROVED** [review]

**Pull request merged**
